<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRghwsio\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRghwsio/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerRghwsio.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerRghwsio\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerRghwsio\appProdProjectContainer([
    'container.build_hash' => 'Rghwsio',
    'container.build_id' => '57f6b38d',
    'container.build_time' => 1671447715,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRghwsio');
