<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZucpokr\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZucpokr/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZucpokr.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZucpokr\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerZucpokr\appDevDebugProjectContainer([
    'container.build_hash' => 'Zucpokr',
    'container.build_id' => '4bc6ce94',
    'container.build_time' => 1671553581,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZucpokr');
