<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHqk1pob\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHqk1pob/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerHqk1pob.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerHqk1pob\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerHqk1pob\appDevDebugProjectContainer([
    'container.build_hash' => 'Hqk1pob',
    'container.build_id' => '6de91c62',
    'container.build_time' => 1671485989,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHqk1pob');
